module.exports = {
    METRO: 'METRO',
    METROED: 'METROED',
    GOT_METROS: 'GOT_METROS',

    GOT_CURRENT_USER: 'GOT_CURRENT_USER',
    GOT_USERS: 'GOT_USERS',

    FOLLOW: 'FOLLOW',
    FOLLOWED: 'FOLLOWED',

    UNFOLLOW: 'UNFOLLOW',
    UNFOLLOWED: 'UNFOLLOWED'
};
